###
GET http://localhost:8000/blogs/

###
GET http://localhost:8000/blogs/2

### 
POST http://localhost:8000/blogs/
Content-Type: application/json

{
    "title": "titulo de prueba",
    "content": "content de prueba"
}

###
PUT http://localhost:8000/blogs/7
Content-Type: application/json

{
    "title": "titulo 7",
    "content": "contenido de mi primer post"
}

###
DELETE http://localhost:8000/blogs/7